name: BoneSkyblock
version: ${version}
description: Boneblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'
author: BonesMgee, DEV_DED
depend: [ Vault ]
softdepend:
  - "MVdWPlaceholderAPI"
  - "PlaceholderAPI"
  - "Essentials"
  - "EssentialsSpawn"
  - "RoseStacker"
  - "WorldEdit"
loadbefore:
  - "Multiverse-Core"
commands:
  iridiumskyblock:
    aliases: [ "island", is ]
    description: Main plugin command
  lobby:
    description: Go to the skyblock lobby
  home:
    description: Go to your skyblock island
